import { useState } from "react";
import { ExternalLink, Heart, StickyNote, Share2, Copy, Send, Linkedin } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { PublicNoteModal } from "./PublicNoteModal";
import { useToast } from "@/hooks/use-toast";
import { regionColor } from "@/lib/regionColor";
import { proxyImage } from "@/lib/imageProxy";
import { isBrandingImage, isAiImage } from "@/lib/brandImage";
import { SnewMark } from "./SnewMark";

// ── Text helpers ──────────────────────────────────────────────────────────────

const decodeEntities = (str: string) => {
  if (!str) return "";
  return str
    .replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(Number(dec)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)))
    .replace(/&quot;/g, '"').replace(/&apos;|&#x27;/g, "'")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ");
};

const stripHtml = (str: string) =>
  str ? str.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim() : "";

const truncateAtNbsp = (str: string) => {
  if (!str) return "";
  const a = str.indexOf("&nbsp;");
  if (a !== -1) return str.slice(0, a).trim();
  const b = str.indexOf(" ");
  if (b !== -1) return str.slice(0, b).trim();
  return str;
};

const cleanSnippet = (str: string) => stripHtml(decodeEntities(truncateAtNbsp(str)));

const getDisplayUrl = (input: string) => {
  if (!input) return input;
  try {
    const urlParamMatch = input.match(/[?&]url=([^&]+)/);
    if (urlParamMatch) {
      const candidate = decodeURIComponent(urlParamMatch[1]);
      if (candidate && !candidate.includes("news.google.com")) return candidate;
    }
    if (input.includes("news.google.com") && input.includes("url=")) {
      const urlMatch = input.match(/url=([^&]+)/);
      if (urlMatch) {
        const decoded = decodeURIComponent(urlMatch[1]);
        if (decoded && !decoded.includes("news.google.com")) return decoded;
      }
    }
  } catch {
    // ignore
  }
  return input;
};

const isSafeExternalUrl = (input?: string | null) => {
  if (!input) return false;
  try {
    const p = new URL(input).protocol;
    return p === "http:" || p === "https:";
  } catch { return false; }
};

// ── Props ─────────────────────────────────────────────────────────────────────

interface ArticleCardProps {
  title: string;
  snippet: string;
  url: string;
  sourceName: string;
  sourceCountry: string;
  sourceRegion: string;
  publishedAt?: string;
  imageUrl?: string | null;
  articleId?: string;
  userId?: string;
  isFavorited?: boolean;
  noteText?: string;
  noteIsPublic?: boolean;
  publicNotes?: Array<{ text: string; userId: string }>;
  onToggleFavorite?: (articleId: string) => void;
  onOpenNotes?: (articleId: string, title: string, noteText?: string, noteIsPublic?: boolean) => void;
  onRequestLogin?: () => void;
  /** When true, renders with larger image and headline (for the lead position). */
  isLead?: boolean;
}

// ── Component ─────────────────────────────────────────────────────────────────

export const ArticleCard = ({
  title, snippet, url, sourceName, sourceCountry, sourceRegion,
  publishedAt, imageUrl, articleId, userId,
  isFavorited = false, noteText, noteIsPublic = false,
  publicNotes = [], onToggleFavorite, onOpenNotes, onRequestLogin,
  isLead = false,
}: ArticleCardProps) => {
  const displayUrl = getDisplayUrl(url);
  const articleUrl = isSafeExternalUrl(displayUrl) ? displayUrl : isSafeExternalUrl(url) ? url : null;
  const [selectedNote, setSelectedNote] = useState<{ text: string; userId: string } | null>(null);
  const [imgError, setImgError] = useState(false);
  const requireLoginToOpen = onRequestLogin && !userId;
  const { toast } = useToast();

  // Show image only when DB has a non-branding URL and it loaded without error.
  // AI illustrations are pre-generated by the backend backfill and stored in image_url.
  const hasImage = !!imageUrl && !isBrandingImage(imageUrl) && !imgError;

  const accent = regionColor(sourceRegion);

  const handleArticleClick = (e: React.MouseEvent) => {
    if (requireLoginToOpen) { e.preventDefault(); onRequestLogin?.(); return; }
    if (!articleUrl) e.preventDefault();
  };

  const shareText = `${decodeEntities(title)} (${sourceName})`;

  const openShareWindow = (shareUrl: string) =>
    window.open(shareUrl, "_blank", "noopener,noreferrer");

  const handleNativeShare = async () => {
    if (!articleUrl) {
      toast({ title: "Sharing unavailable", description: "No valid URL for this article.", variant: "destructive" });
      return;
    }
    if (typeof navigator !== "undefined" && navigator.share) {
      try { await navigator.share({ title: decodeEntities(title), text: shareText, url: articleUrl }); return; } catch { /* user cancelled share dialog */ }
    }
    try {
      await navigator.clipboard.writeText(articleUrl);
      toast({ title: "Link copied", description: "Article link copied to your clipboard." });
    } catch {
      toast({ title: "Sharing unavailable", description: "Unable to copy link.", variant: "destructive" });
    }
  };

  const handleSocialShare = (platform: "x" | "linkedin") => {
    if (!articleUrl) {
      toast({ title: "Sharing unavailable", description: "No valid URL for this article.", variant: "destructive" });
      return;
    }
    if (platform === "x") {
      openShareWindow(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(articleUrl)}`);
    } else {
      openShareWindow(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(articleUrl)}`);
    }
  };

  const isPoster = isLead && !hasImage;
  // Use full image height when there's an image; smaller backdrop when logo-only.
  const imgHeight = hasImage ? (isLead ? 224 : 152) : (isLead ? 96 : 72);
  const titleSize = hasImage ? (isLead ? 20 : 15.5) : (isLead ? 28 : 21);
  const snippetLines = hasImage ? (isLead ? 4 : 3) : (isLead ? 6 : 5);

  return (
    <article
      style={{
        background: "hsl(var(--card))",
        border: "1px solid hsl(var(--border))",
        borderLeft: `3px solid ${accent}`,
        borderRadius: "var(--radius)",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        height: "100%",
        transition: "box-shadow .15s ease",
      }}
      onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "0 4px 20px hsl(var(--shadow))"; }}
      onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "none"; }}
    >
      {/* Thumbnail — real photo, AI illustration, or branded Snew-mark backdrop */}
      {hasImage ? (
        <a href={articleUrl || "#"} target="_blank" rel="noopener noreferrer"
          style={{
            display: "block", overflow: "hidden", position: "relative",
            // Lead image grows to fill the column height; grid cards use a fixed height.
            ...(isLead
              ? { flex: "1 0 0", minHeight: 200 }
              : { flexShrink: 0, height: imgHeight }),
          }}
          onClick={handleArticleClick}
          aria-label={`Open: ${decodeEntities(title)}`}
        >
          <img
            src={proxyImage(imageUrl, { width: isLead ? 900 : 540 }) ?? undefined}
            alt={title}
            onError={() => setImgError(true)}
            referrerPolicy="no-referrer"
            style={{ width: "100%", height: isLead ? "100%" : imgHeight, objectFit: "cover", display: "block" }}
            loading="lazy" decoding="async"
          />
          {/* AI illustration label — shown only when the image was AI-generated */}
          {isAiImage(imageUrl) && (
            <span style={{
              position: "absolute", bottom: 6, left: 8,
              fontFamily: '"IBM Plex Mono", monospace',
              fontSize: 9, letterSpacing: "0.08em",
              color: "rgba(255,255,255,0.82)",
              background: "rgba(0,0,0,0.45)",
              padding: "2px 6px", borderRadius: 3,
              userSelect: "none", pointerEvents: "none",
            }}>AI illustration</span>
          )}
        </a>
      ) : (
        /* Snew-mark backdrop — branded "no photo" treatment for lead and grid cards */
        <div
          aria-hidden="true"
          style={{
            height: imgHeight,
            flexShrink: 0,
            background: `color-mix(in srgb, ${accent} 16%, hsl(var(--card)))`,
            borderBottom: `1px solid color-mix(in srgb, ${accent} 28%, transparent)`,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            position: "relative",
            overflow: "hidden",
          }}
        >
          <SnewMark size={isPoster ? 96 : 40} />
        </div>
      )}

      {/* Body — lead with image: fixed height (image fills remaining space); everything else: flex-grow */}
      <div style={{ padding: "14px 16px", display: "flex", flexDirection: "column", flex: isLead && hasImage ? "0 0 auto" : 1, gap: 10 }}>
        {/* Region / country pills */}
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
          <span style={{
            fontSize: 10.5, fontWeight: 600, letterSpacing: "0.06em",
            padding: "2px 8px", borderRadius: 99,
            background: `color-mix(in srgb, ${accent} 12%, transparent)`,
            color: accent, border: `1px solid color-mix(in srgb, ${accent} 25%, transparent)`,
          }}>{sourceRegion}</span>
          <span style={{
            fontSize: 10.5, fontWeight: 500, padding: "2px 8px", borderRadius: 99,
            border: "1px solid hsl(var(--border))", color: "hsl(var(--muted-foreground))",
          }}>{sourceCountry}</span>
        </div>

        {/* Headline */}
        <h3 style={{ margin: 0, fontFamily: "Newsreader, serif", fontSize: titleSize, fontWeight: 600, lineHeight: 1.35 }}>
          <a
            href={articleUrl || "#"} target="_blank" rel="noopener noreferrer"
            onClick={handleArticleClick}
            style={{ color: "hsl(var(--foreground))", textDecoration: "none", display: "flex", alignItems: "flex-start", gap: 6 }}
          >
            <span style={{ flex: 1 }}>{decodeEntities(title)}</span>
            <ExternalLink size={13} style={{ flexShrink: 0, marginTop: 3, color: "hsl(var(--muted-foreground))", opacity: 0.5 }} />
          </a>
        </h3>

        {/* Snippet */}
        <p style={{
          margin: 0, fontSize: 13, color: "hsl(var(--muted-foreground))", lineHeight: 1.55,
          display: "-webkit-box", WebkitLineClamp: snippetLines,
          WebkitBoxOrient: "vertical", overflow: "hidden", flex: 1,
        }}>
          {cleanSnippet(snippet)}
        </p>

        {/* Dateline */}
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "center",
          paddingTop: 8, borderTop: "1px solid hsl(var(--border))",
          fontFamily: '"IBM Plex Mono", monospace', fontSize: 10.5,
        }}>
          <span style={{ fontWeight: 600, color: "hsl(var(--foreground))", opacity: 0.65 }}>{sourceName}</span>
          {publishedAt && (
            <span style={{ color: "hsl(var(--muted-foreground))" }}>
              {new Date(publishedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
            </span>
          )}
        </div>

        {/* Public notes from other users */}
        {publicNotes.length > 0 && (
          <div style={{ marginTop: 4 }}>
            <p style={{ fontSize: 11, fontWeight: 600, color: "hsl(var(--muted-foreground))", marginBottom: 6 }}>Public Notes:</p>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {publicNotes.map((note, idx) => {
                const isLong = note.text.length > 100;
                return (
                  <button
                    key={idx} type="button"
                    onClick={() => isLong && setSelectedNote(note)}
                    disabled={!isLong}
                    style={{
                      textAlign: "left", fontSize: 11.5,
                      background: "hsl(var(--secondary))", border: 0,
                      borderLeft: `2px solid hsl(var(--primary))`,
                      padding: "6px 10px", borderRadius: 2,
                      cursor: isLong ? "pointer" : "default",
                      color: "hsl(var(--foreground))",
                    }}
                  >
                    {isLong ? note.text.slice(0, 100) + "…" : note.text}
                    {isLong && <span style={{ display: "block", fontSize: 10.5, color: "hsl(var(--primary))", marginTop: 3 }}>Read more…</span>}
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* Action buttons */}
        {articleId && (
          <div style={{ borderTop: "1px solid hsl(var(--border))", paddingTop: 8, marginTop: 2 }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 2 }}>
              <TooltipProvider>
                <Tooltip><TooltipTrigger asChild>
                  <Button variant="ghost" size="sm" onClick={handleNativeShare} aria-label="Share article"
                    className="h-9 w-9 p-0 text-muted-foreground hover:text-foreground">
                    <Share2 size={14} />
                  </Button>
                </TooltipTrigger><TooltipContent><p>Share or copy link</p></TooltipContent></Tooltip>

                <Tooltip><TooltipTrigger asChild>
                  <Button variant="ghost" size="sm" onClick={() => handleSocialShare("x")} aria-label="Share to X"
                    className="h-9 w-9 p-0 text-muted-foreground hover:text-foreground">
                    <Send size={14} />
                  </Button>
                </TooltipTrigger><TooltipContent><p>Share to X</p></TooltipContent></Tooltip>

                <Tooltip><TooltipTrigger asChild>
                  <Button variant="ghost" size="sm" onClick={() => handleSocialShare("linkedin")} aria-label="Share to LinkedIn"
                    className="h-9 w-9 p-0 text-muted-foreground hover:text-foreground">
                    <Linkedin size={14} />
                  </Button>
                </TooltipTrigger><TooltipContent><p>Share to LinkedIn</p></TooltipContent></Tooltip>

                <Tooltip><TooltipTrigger asChild>
                  <Button variant="ghost" size="sm" aria-label="Copy link"
                    className="h-9 w-9 p-0 text-muted-foreground hover:text-foreground"
                    onClick={async () => {
                      if (!articleUrl) { toast({ title: "Copy unavailable", description: "No valid URL.", variant: "destructive" }); return; }
                      try { await navigator.clipboard.writeText(articleUrl); toast({ title: "Copied", description: "Article URL copied." }); }
                      catch { toast({ title: "Copy unavailable", description: "Could not copy URL.", variant: "destructive" }); }
                    }}>
                    <Copy size={14} />
                  </Button>
                </TooltipTrigger><TooltipContent><p>Copy link</p></TooltipContent></Tooltip>

                {userId && (
                  <>
                    <Tooltip><TooltipTrigger asChild>
                      <Button variant="ghost" size="sm"
                        onClick={() => onToggleFavorite?.(articleId)}
                        aria-label={isFavorited ? "Remove from favorites" : "Add to favorites"}
                        className={`h-9 w-9 p-0 transition-colors ${isFavorited ? "text-red-500 hover:text-red-600" : "text-muted-foreground hover:text-red-500"}`}>
                        <Heart size={14} className={isFavorited ? "fill-current" : ""} />
                      </Button>
                    </TooltipTrigger><TooltipContent><p>{isFavorited ? "Remove from Favorites" : "Add to Favorites"}</p></TooltipContent></Tooltip>

                    <Tooltip><TooltipTrigger asChild>
                      <Button variant="ghost" size="sm"
                        onClick={() => onOpenNotes?.(articleId, title, noteText, noteIsPublic)}
                        aria-label={noteText ? "Edit note" : "Add note"}
                        className="h-9 w-9 p-0 text-muted-foreground hover:text-foreground relative">
                        <StickyNote size={14} />
                        {noteText && <span style={{ position: "absolute", top: 1, right: 1, width: 7, height: 7, borderRadius: "50%", background: "hsl(var(--primary))" }} />}
                      </Button>
                    </TooltipTrigger><TooltipContent><p>{noteText ? "Edit Note" : "Add Note"}</p></TooltipContent></Tooltip>
                  </>
                )}
              </TooltipProvider>
            </div>
            {!userId && onRequestLogin && (
              <p style={{ fontSize: 11, marginTop: 4, textAlign: "center" }}>
                <button type="button" onClick={onRequestLogin}
                  style={{ color: "hsl(var(--muted-foreground))", textDecoration: "underline", border: 0, background: "none", cursor: "pointer", fontSize: 11 }}>
                  Log in to use favorites and notes
                </button>
              </p>
            )}
          </div>
        )}
      </div>

      {selectedNote && (
        <PublicNoteModal isOpen={!!selectedNote} onClose={() => setSelectedNote(null)}
          noteText={selectedNote.text} userId={selectedNote.userId} />
      )}
    </article>
  );
};
